#!/usr/bin/env python3
"""
Config Manager – Backup Engine
Uses Netmiko to connect to network devices and retrieve running configurations.

Usage:
    python3 backup.py --ip 192.168.1.1 --vendor cisco_ios \
        --user admin --pass secret --port 22 --out /opt/config-backups/Router1/2026-06-20_0100.cfg

Requirements:
    pip3 install netmiko
"""

import argparse
import os
import re
import sys
import traceback
from pathlib import Path

try:
    from netmiko import ConnectHandler
    from netmiko.exceptions import (
        NetmikoTimeoutException,
        NetmikoAuthenticationException,
    )
except ImportError:
    print("ERROR: netmiko is not installed. Run: pip3 install netmiko", file=sys.stderr)
    sys.exit(1)


VENDOR_MAP = {
    "cisco_ios": {
        "device_type_ssh":    "cisco_ios",
        "device_type_telnet": "cisco_ios_telnet",
        "commands": ["show running-config"],
        "strip_headers": True,
    },
    "cisco_nxos": {
        "device_type_ssh":    "cisco_nxos",
        "device_type_telnet": "cisco_nxos_telnet",
        "commands": ["show running-config"],
        "strip_headers": False,
    },
    "fortinet": {
        "device_type_ssh":    "fortinet",
        # Netmiko has no dedicated Fortinet telnet driver (FortiOS telnet
        # management is uncommon/disabled by default on most builds).
        # generic_telnet works for basic line-mode CLI output if telnet is
        # explicitly enabled on the device.
        "device_type_telnet": "generic_telnet",
        "commands": ["show full-configuration"],
        "strip_headers": False,
    },
    "mikrotik": {
        "device_type_ssh":    "mikrotik_routeros",
        # No dedicated Netmiko telnet driver for RouterOS either.
        "device_type_telnet": "generic_telnet",
        "commands": ["/export"],
        "strip_headers": True,   # MikroTik also adds a timestamp line
    },
    "juniper": {
        "device_type_ssh":    "juniper_junos",
        "device_type_telnet": "juniper_junos_telnet",
        "commands": ["show configuration"],
        "strip_headers": False,
    },
    "netgear": {
        "device_type_ssh":    "netgear_prosafe",
        # No dedicated Netmiko telnet driver for Netgear ProSafe either;
        # generic_telnet handles its simple menu-free CLI reasonably well.
        "device_type_telnet": "generic_telnet",
        "commands": ["show running-config"],
        "strip_headers": False,
    },
}

# Vendors where Netmiko has a purpose-built _telnet driver. For everything
# else we fall back to generic_telnet, which is less robust (no vendor-
# specific prompt handling) — flagged to the caller via a warning at runtime.
VENDORS_WITH_NATIVE_TELNET = {"cisco_ios", "cisco_nxos", "juniper"}

# Vendors whose CLI boots into an unprivileged user-EXEC prompt over telnet
# (e.g. Netgear ProSafe lands on "(hostname) >") where "show" commands are
# rejected with "% Invalid input detected" until "enable" is sent to reach
# the privileged "(hostname) #" prompt. The dedicated cisco_ios_telnet/
# cisco_nxos_telnet drivers already handle this themselves; generic_telnet
# has no vendor awareness and needs to be told explicitly.
VENDORS_REQUIRING_ENABLE = {"netgear"}

# Lines whose content changes every run but carry no config meaning.
# Stripping them prevents false "config changed" detections.
NOISE_PATTERNS = [
    "Building configuration",
    "Current configuration",
    "Load for five",
    "Time source is",
    "! Last configuration change",
    "! NVRAM config last updated",
    "# generated by",          # MikroTik timestamp line
    "# by RouterOS",           # MikroTik version line that may change
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Config Manager – Device Backup")
    parser.add_argument("--ip",      required=True,  help="Device IP address")
    parser.add_argument("--vendor",  required=True,  choices=list(VENDOR_MAP.keys()))
    parser.add_argument("--user",    required=True,  help="SSH username")
    parser.add_argument("--pass",    required=True,  dest="password", help="SSH password")
    parser.add_argument("--enable-secret", default=None,
                         help="Enable/privileged-mode password, if different "
                              "from --pass (only used for vendors that "
                              "require an enable step over telnet, e.g. Netgear)")
    parser.add_argument("--port",    type=int, default=22, help="SSH port (default 22)")
    parser.add_argument("--method",  choices=["ssh", "telnet"], default="ssh",
                         help="Connection method (default ssh)")
    parser.add_argument("--out",     required=True,  help="Output file path")
    parser.add_argument("--timeout", type=int, default=30, help="Connection timeout seconds")
    return parser.parse_args()


def ensure_dir(filepath: str) -> None:
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)


def strip_noise(output: str) -> str:
    """
    Remove lines that change on every backup but carry no config meaning.
    This prevents false 'config changed' detections caused by timestamps
    and counters that Cisco/MikroTik embed in their output.
    """
    lines = output.splitlines()
    result = []
    for line in lines:
        stripped = line.strip()
        if any(stripped.startswith(p) or p in stripped for p in NOISE_PATTERNS):
            continue
        result.append(line)
    return "\n".join(result)


def enter_enable_mode(conn, args: argparse.Namespace) -> None:
    """
    Send 'enable' to escalate from user EXEC to privileged EXEC mode on
    devices that need it (see VENDORS_REQUIRING_ENABLE). Uses
    send_command_timing rather than Netmiko's built-in conn.enable(),
    since generic_telnet has no vendor-specific prompt patterns for
    enable() to rely on.
    """
    print("[INFO] Entering privileged (enable) mode...")
    output = conn.send_command_timing(
        "enable",
        strip_prompt=False,
        strip_command=False,
    )

    # If the device echoes our "enable" command right back after a "User:"
    # prompt (i.e. "User:enable"), the session was never actually past the
    # login screen when we got here - it took "enable" as a username, not
    # a mode-change command. Sending a password next would just attempt a
    # login as user "enable" and fail confusingly, so catch it here with a
    # clear diagnosis instead. On these switches this has been caused by a
    # stale telnet session (they often allow only one at a time) still
    # holding the device's session slot - check for other open sessions
    # to this device and close them before retrying.
    if re.search(r"user\s*:\s*enable", output, re.IGNORECASE):
        raise RuntimeError(
            "Device returned a fresh login prompt instead of an enable "
            "sequence - the telnet session was never authenticated before "
            "this step ran. This switch likely allows only one telnet "
            "session at a time; check for and close any other open "
            f"session to this device before retrying. Raw output: {output!r}"
        )

    if "assword" in output.lower():
        secret = args.enable_secret or args.password
        output += conn.send_command_timing(
            secret,
            strip_prompt=False,
            strip_command=False,
        )

    if "#" not in output:
        raise RuntimeError(
            "Failed to enter privileged (enable) mode: device did not "
            f"return a '#' prompt after 'enable'. Output was: {output!r}"
        )

    # The prompt terminator just changed from '>' to '#'. Netmiko cached
    # the '>' prompt during session setup and uses it to detect when a
    # send_command() response is complete, so refresh it now or every
    # subsequent command will time out waiting for a prompt that never
    # reappears in that form.
    conn.set_base_prompt()


def backup_device(args: argparse.Namespace) -> str:
    vendor_cfg = VENDOR_MAP[args.vendor]

    if args.method == "telnet":
        device_type = vendor_cfg["device_type_telnet"]
        if args.vendor not in VENDORS_WITH_NATIVE_TELNET:
            print(f"[WARN] Netmiko has no dedicated Telnet driver for "
                  f"'{args.vendor}'; using generic_telnet. This is less "
                  f"reliable than SSH — verify the backup output looks "
                  f"correct.", file=sys.stderr)
    else:
        device_type = vendor_cfg["device_type_ssh"]

    device_params = {
        "device_type": device_type,
        "host":        args.ip,
        "username":    args.user,
        "password":    args.password,
        "port":        args.port,
        "timeout":     args.timeout,
        "conn_timeout": args.timeout,
        "session_log": None,
    }

    if args.vendor == "juniper":
        device_params["fast_cli"] = False

    print(f"[INFO] Connecting to {args.ip} ({args.vendor} via {args.method}) on port {args.port}...")

    with ConnectHandler(**device_params) as conn:
        print(f"[INFO] Connected. Retrieving configuration...")

        if args.method == "telnet" and args.vendor in VENDORS_REQUIRING_ENABLE:
            enter_enable_mode(conn, args)

        full_output = []
        for cmd in vendor_cfg["commands"]:
            print(f"[INFO] Running: {cmd}")
            if args.vendor == "cisco_ios":
                output = conn.send_command(
                    cmd,
                    expect_string=r"#",
                    read_timeout=60,
                    strip_prompt=True,
                    strip_command=True,
                )
            else:
                output = conn.send_command(
                    cmd,
                    read_timeout=60,
                    strip_prompt=True,
                    strip_command=True,
                )
            full_output.append(output)

    config_text = "\n".join(full_output)

    # Always strip noise lines — never write timestamps into the config file
    config_text = strip_noise(config_text)

    return config_text.strip()


def main() -> None:
    args = parse_args()

    try:
        ensure_dir(args.out)
        config_text = backup_device(args)

        if not config_text:
            print("[ERROR] Empty configuration received.", file=sys.stderr)
            sys.exit(1)

        # Write ONLY the device config — no timestamps, no metadata headers.
        # The backup filename already encodes the date/time.
        # Adding any time-varying content here would cause false change detections.
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(config_text)
            f.write("\n")

        size_kb = os.path.getsize(args.out) / 1024
        print(f"[OK] Backup saved to: {args.out} ({size_kb:.1f} KB)")
        sys.exit(0)

    except NetmikoAuthenticationException as e:
        print(f"[ERROR] Authentication failed: {e}", file=sys.stderr)
        sys.exit(1)

    except NetmikoTimeoutException as e:
        print(f"[ERROR] Connection timed out: {e}", file=sys.stderr)
        sys.exit(1)

    except Exception as e:
        print(f"[ERROR] Unexpected error: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
